mysql:
  image: "mysql:5.6"
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: password
postgres:
  image: "postgres:9.4"
  ports:
    - "5432:5432"
  environment:
    POSTGRES_PASSWORD: postgres
